---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify_intent(classify_intent)
	handle_content_generation(handle_content_generation)
	handle_analytics(handle_analytics)
	handle_leads_management(handle_leads_management)
	handle_posting_manager(handle_posting_manager)
	handle_general_talks(handle_general_talks)
	generate_final_response(generate_final_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify_intent;
	classify_intent -. &nbsp;analytics&nbsp; .-> handle_analytics;
	classify_intent -. &nbsp;content_generation&nbsp; .-> handle_content_generation;
	classify_intent -. &nbsp;general_talks&nbsp; .-> handle_general_talks;
	classify_intent -. &nbsp;leads_management&nbsp; .-> handle_leads_management;
	classify_intent -. &nbsp;posting_manager&nbsp; .-> handle_posting_manager;
	handle_analytics --> generate_final_response;
	handle_content_generation --> generate_final_response;
	handle_general_talks --> generate_final_response;
	handle_leads_management --> generate_final_response;
	handle_posting_manager --> generate_final_response;
	generate_final_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
